# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a390b9c26a3657e98ae6ff082531ba7c090075394e9341242a7c9a01d1647f6581fa1ee5d7659e413542da36e1d2f0e046126caa3eb377e5b148b162bb40e24b

test:
  secret_key_base: efaf148d388040d9a5dd976838022df8df62afeaccdbb9f084f738d9bb9f35430160ac00271601e7c40a0d2682fcfc1e63875615f754184b3fad42cd4863833b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
